# Generated by Django 4.2.11 on 2024-03-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0003_customer_referral_code_referral_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
