# Generated by Django 4.2.11 on 2024-03-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0006_customer_profile_photo_manualverification_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
