# Generated by Django 4.2.11 on 2024-03-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0007_customer_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServiceConstants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
