# Generated by Django 4.2.11 on 2024-03-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletservice', '0002_customer_alter_wallet_id_validation_authentication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='validation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Authentication',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Validation',
        ),
    ]
