# Generated by Django 4.2.11 on 2024-03-23 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0002_alter_authentication_user'),
        ('walletservice', '0006_alter_wallettransactionsmetadata_transfer_to_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandiPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=256)),
                ('images', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userservice.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MandiPriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('product_id', models.BigIntegerField(null=True)),
                ('sku_id', models.BigIntegerField(null=True)),
                ('mandi_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletservice.mandiprice')),
            ],
        ),
    ]
