# Generated by Django 4.2.11 on 2024-03-21 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('language', models.CharField(default='en', max_length=20)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('velynk_customer_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.appcustomer')),
            ],
        ),
    ]
